// <auto-generated />
using System;
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230109114632_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "6b28e4a5-a04a-4354-b15c-9ae47dd31e89",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8199),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Dynamic Intranet Technician",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8214)
                        },
                        new
                        {
                            Id = "042363ff-333a-4c30-8d59-4d89693567ca",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8715),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Senior Assurance Officer",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8718)
                        },
                        new
                        {
                            Id = "248601e1-12b9-45f7-b410-a2904baf9519",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8784),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Human Mobility Associate",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8785)
                        },
                        new
                        {
                            Id = "2d6040ea-898a-4c34-acaf-196d82e338f8",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8825),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Product Intranet Technician",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8826)
                        },
                        new
                        {
                            Id = "7d4468d1-b273-4159-b407-79409755ccea",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8860),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Global Tactics Executive",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8862)
                        },
                        new
                        {
                            Id = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8997),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Principal Functionality Planner",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(8999)
                        },
                        new
                        {
                            Id = "92dbfd1a-dbe6-476c-b0e4-3086c5a9fca7",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9042),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Human Web Coordinator",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9044)
                        },
                        new
                        {
                            Id = "e9369b42-b63c-4240-97ad-d4843e72fde3",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9080),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Dynamic Directives Consultant",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9081)
                        },
                        new
                        {
                            Id = "a5f62fb1-08a6-455c-9972-f60f53103d46",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9116),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Regional Brand Supervisor",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9118)
                        },
                        new
                        {
                            Id = "29b2cde0-08ce-4496-8905-e44cb83d394f",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9162),
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Senior Division Analyst",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 798, DateTimeKind.Local).AddTicks(9164)
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Models.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gallary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1c1efa46-bfc7-464c-b432-5c88d75030b2",
                            CategoryId = "92dbfd1a-dbe6-476c-b0e4-3086c5a9fca7",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(2195),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Small Fresh Towels",
                            Price = "343.56",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(2201)
                        },
                        new
                        {
                            Id = "8c9fe969-34b5-44a3-b941-d30e69d92b42",
                            CategoryId = "92dbfd1a-dbe6-476c-b0e4-3086c5a9fca7",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3000),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handcrafted Granite Chips",
                            Price = "55.44",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3003)
                        },
                        new
                        {
                            Id = "d7488c60-efd5-429b-83ae-eb1420f5d62c",
                            CategoryId = "248601e1-12b9-45f7-b410-a2904baf9519",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3188),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Practical Metal Chair",
                            Price = "802.96",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3190)
                        },
                        new
                        {
                            Id = "37c3545c-bc0f-4654-8996-588a8519315c",
                            CategoryId = "92dbfd1a-dbe6-476c-b0e4-3086c5a9fca7",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3275),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handcrafted Concrete Pizza",
                            Price = "608.44",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3276)
                        },
                        new
                        {
                            Id = "2206b956-8eb5-477d-b73d-4c8efcdb21f3",
                            CategoryId = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3340),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Sleek Rubber Salad",
                            Price = "703.83",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3342)
                        },
                        new
                        {
                            Id = "48e3e58e-14c1-4059-a14e-de6fb9cb8731",
                            CategoryId = "2d6040ea-898a-4c34-acaf-196d82e338f8",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3405),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handcrafted Fresh Chips",
                            Price = "148.70",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3407)
                        },
                        new
                        {
                            Id = "c534b321-fadf-47cd-96d6-95b7bda79fb0",
                            CategoryId = "248601e1-12b9-45f7-b410-a2904baf9519",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3465),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Sleek Fresh Pizza",
                            Price = "339.08",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3467)
                        },
                        new
                        {
                            Id = "64f74df0-d171-4fe4-bb99-95e7a602abcb",
                            CategoryId = "7d4468d1-b273-4159-b407-79409755ccea",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3538),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Incredible Plastic Fish",
                            Price = "155.19",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3539)
                        },
                        new
                        {
                            Id = "7fd9b1ec-44dc-43a1-ba4a-2bc219ed7320",
                            CategoryId = "6b28e4a5-a04a-4354-b15c-9ae47dd31e89",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3603),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Rustic Fresh Fish",
                            Price = "419.12",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3604)
                        },
                        new
                        {
                            Id = "b70bae59-bd65-44be-9340-018c58f4ed50",
                            CategoryId = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3662),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Ergonomic Cotton Chicken",
                            Price = "835.66",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3664)
                        },
                        new
                        {
                            Id = "c451a2e7-a131-4ccb-b677-51d24f50e9d0",
                            CategoryId = "7d4468d1-b273-4159-b407-79409755ccea",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3724),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handcrafted Steel Gloves",
                            Price = "580.51",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3726)
                        },
                        new
                        {
                            Id = "eeed12ea-0960-4d4a-8193-49f06aa1e498",
                            CategoryId = "29b2cde0-08ce-4496-8905-e44cb83d394f",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3864),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Unbranded Fresh Soap",
                            Price = "810.89",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3867)
                        },
                        new
                        {
                            Id = "c2545b5a-ae93-401a-8a69-9855478224ca",
                            CategoryId = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3931),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Tasty Metal Table",
                            Price = "44.45",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3933)
                        },
                        new
                        {
                            Id = "27880ba7-b238-4a5b-a618-438d718a0b66",
                            CategoryId = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3993),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handcrafted Wooden Towels",
                            Price = "899.70",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(3995)
                        },
                        new
                        {
                            Id = "64a186c0-376a-40af-87ce-14f91dc86c28",
                            CategoryId = "e9369b42-b63c-4240-97ad-d4843e72fde3",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4052),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Handmade Frozen Soap",
                            Price = "414.09",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4053)
                        },
                        new
                        {
                            Id = "29e718e5-ada7-4118-8fee-0bacd05198b3",
                            CategoryId = "7d4468d1-b273-4159-b407-79409755ccea",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4115),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Rustic Wooden Chicken",
                            Price = "209.85",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4117)
                        },
                        new
                        {
                            Id = "7ef867e1-d457-48a4-a3a1-c7692a122c41",
                            CategoryId = "e9369b42-b63c-4240-97ad-d4843e72fde3",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4176),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Ergonomic Plastic Bacon",
                            Price = "195.10",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4178)
                        },
                        new
                        {
                            Id = "c18ae125-61f7-44d0-b2ed-e91fe5a2e650",
                            CategoryId = "67010fb0-380e-4a58-afb6-a32c80328756",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4235),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Refined Plastic Shoes",
                            Price = "558.79",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4236)
                        },
                        new
                        {
                            Id = "aa1f8d45-0cf6-40c0-be49-ebb19897f1fc",
                            CategoryId = "6b28e4a5-a04a-4354-b15c-9ae47dd31e89",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4294),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Intelligent Fresh Ball",
                            Price = "382.15",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4296)
                        },
                        new
                        {
                            Id = "778a3751-cb93-4c49-a5d8-9a3c0e0fe904",
                            CategoryId = "e9369b42-b63c-4240-97ad-d4843e72fde3",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4431),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Gorgeous Steel Computer",
                            Price = "459.65",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4433)
                        },
                        new
                        {
                            Id = "6d0f3601-3484-477a-a220-77481d70c745",
                            CategoryId = "6b28e4a5-a04a-4354-b15c-9ae47dd31e89",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4497),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Licensed Concrete Keyboard",
                            Price = "651.80",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4499)
                        },
                        new
                        {
                            Id = "7c0a7cd2-8ada-434b-b2ea-cf5c06718483",
                            CategoryId = "92dbfd1a-dbe6-476c-b0e4-3086c5a9fca7",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4557),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Practical Granite Tuna",
                            Price = "715.11",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4559)
                        },
                        new
                        {
                            Id = "2061633e-267c-43bf-9744-5b663f103661",
                            CategoryId = "2d6040ea-898a-4c34-acaf-196d82e338f8",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4615),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Practical Soft Pizza",
                            Price = "479.01",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4616)
                        },
                        new
                        {
                            Id = "5bf8c14b-924a-4f06-b31d-8f5e52b4a430",
                            CategoryId = "a5f62fb1-08a6-455c-9972-f60f53103d46",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4678),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Ergonomic Wooden Bacon",
                            Price = "329.08",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4680)
                        },
                        new
                        {
                            Id = "70983f58-ac84-432c-ac31-60df3fd5fac5",
                            CategoryId = "042363ff-333a-4c30-8d59-4d89693567ca",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4741),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Generic Soft Bacon",
                            Price = "471.42",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4742)
                        },
                        new
                        {
                            Id = "4c9341d9-011a-4f9f-a030-07a3caa1cc76",
                            CategoryId = "2d6040ea-898a-4c34-acaf-196d82e338f8",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4798),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Licensed Granite Tuna",
                            Price = "76.31",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4800)
                        },
                        new
                        {
                            Id = "3394f804-7979-4fa7-abe4-65d4ca27ed02",
                            CategoryId = "29b2cde0-08ce-4496-8905-e44cb83d394f",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4855),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Intelligent Wooden Computer",
                            Price = "290.17",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4857)
                        },
                        new
                        {
                            Id = "5f7828ba-97e1-4b54-919a-6081e1fcf350",
                            CategoryId = "6b28e4a5-a04a-4354-b15c-9ae47dd31e89",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4981),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Unbranded Steel Salad",
                            Price = "481.96",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(4983)
                        },
                        new
                        {
                            Id = "4209a3dc-ba6e-4ad5-90da-e68434d451e2",
                            CategoryId = "248601e1-12b9-45f7-b410-a2904baf9519",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(5053),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Incredible Fresh Table",
                            Price = "876.42",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(5055)
                        },
                        new
                        {
                            Id = "8cb24457-f253-4f1c-b49d-1bf55467ac37",
                            CategoryId = "29b2cde0-08ce-4496-8905-e44cb83d394f",
                            CreatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(5111),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Gallary = "[\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\",\"https://picsum.photos/seed/picsum/1080/800\"]",
                            Image = "https://picsum.photos/seed/picsum/1080/800",
                            IsDeleted = false,
                            Name = "Tasty Cotton Car",
                            Price = "891.82",
                            UpdatedAt = new DateTime(2023, 1, 9, 18, 46, 31, 802, DateTimeKind.Local).AddTicks(5113)
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2dfb43f4-24d5-44a7-af3c-78196e881f23",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5679e770-dd4a-43b0-ab78-f212ac6abf3b",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEL9mII8beu8tjw6mh5JAHpWuTWg1l7+tgRnvYClpWpjRh436/61C4W2D087Bn8efjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28a3794d-0255-43b1-966b-8b060bd97e04",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "75fa9827-0f5f-41db-a825-64d68d242d7e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be83d6ec-33e7-4cbc-827a-5d855ea178ee",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAEAACcQAAAAED5zOQ+dt8K/cxCZeSG0A1dl9HZ6IAie9NS3ac+ccp9ZO7yY1C8cucoF1nTZyDQUGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "61a0c15f-984c-4902-beb1-bc8c66fa78e6",
                            TwoFactorEnabled = false,
                            UserName = "User"
                        },
                        new
                        {
                            Id = "df31566d-5ccb-45dc-b1be-864d72133ca4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e7e22f8-c1a7-4095-87e0-7a8cc29c1740",
                            Email = "guest@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST@GMAIL.COM",
                            NormalizedUserName = "GUEST",
                            PasswordHash = "AQAAAAEAACcQAAAAEMRbNZ3zxaCSA+mplWJ8NiHnz/T1r2kYSOjXQlUlQNAt2yp0R7Z4q/V6CGRs/Qiwfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "470f9060-dbd2-4d90-826f-5557c62f8375",
                            TwoFactorEnabled = false,
                            UserName = "Guest"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2dfb43f4-24d5-44a7-af3c-78196e881f23",
                            RoleId = "cc3b4c20-7ab3-4daa-b777-0018ee8c615c"
                        },
                        new
                        {
                            UserId = "75fa9827-0f5f-41db-a825-64d68d242d7e",
                            RoleId = "dddd1a59-3b57-45f6-96b5-91b3e269e87c"
                        },
                        new
                        {
                            UserId = "df31566d-5ccb-45dc-b1be-864d72133ca4",
                            RoleId = "b600478d-f98b-4a27-aa95-14563920d28f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Models.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "cc3b4c20-7ab3-4daa-b777-0018ee8c615c",
                            ConcurrencyStamp = "05a04d2d-ae33-4e9d-9e6b-9fa1e66a3041",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "dddd1a59-3b57-45f6-96b5-91b3e269e87c",
                            ConcurrencyStamp = "f83bfd7a-8dc1-445d-8d83-e5a07938daff",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "b600478d-f98b-4a27-aa95-14563920d28f",
                            ConcurrencyStamp = "911f910b-2071-47b7-ac15-321e54e05c3b",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Order", b =>
                {
                    b.HasOne("Ecommerce.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Models.OrderDetail", b =>
                {
                    b.HasOne("Ecommerce.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("Ecommerce.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ecommerce.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
